# Generated by Django 3.2.10 on 2021-12-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
