# Generated by Django 3.2.10 on 2021-12-30 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_user_app', '0002_alter_userprofileinfo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='password_confirm',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='verification_email',
        ),
    ]
